### ISSUE TITLE
traceback in test_tmx_hexmap.py with py35

### ISSUE THREAD

**Issue by ccanepa** [los-cocos/cocos#263]
traceback in test_tmx_hexmap.py with py35 64bits on Windows:
```
Traceback (most recent call last):
  File "F:/para_BA/_dev/cocos/test/test_tmx_hexmap.py", line 128, in <module>
    main()
  File "F:/para_BA/_dev/cocos/test/test_tmx_hexmap.py", line 59, in main
    scroller.add(test_layer)
  File "F:/para_BA/_dev/cocos/test\..\cocos\layer\scrolling.py", line 249, in add
    self.set_focus(self.fx, self.fy, force=True)
  File "F:/para_BA/_dev/cocos/test\..\cocos\layer\scrolling.py", line 374, in set_focus
    self.view_x / self.scale, self.view_y / self.scale)
  File "F:/para_BA/_dev/cocos/test\..\cocos\tiles.py", line 758, in set_view
    self._update_sprite_set()
  File "F:/para_BA/_dev/cocos/test\..\cocos\tiles.py", line 824, in _update_sprite_set
    for cell in self.get_visible_cells():
  File "F:/para_BA/_dev/cocos/test\..\cocos\tiles.py", line 770, in get_visible_cells
    return self.get_in_region(x, y, x + w, y + h)
  File "F:/para_BA/_dev/cocos/test\..\cocos\tiles.py", line 1341, in get_in_region
    return [self.cells[i][j] for i in range(left, right) for j in range(bottom, top)]
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by dangillet** [comment]
Hello,

This is due to the change I made a while ago in this commit e2d77d35 due to issue #253.

As you said:
> I suggest landing the change on master, and later fix problems if they appear.

So here we are.

 I made the necessary corrections I think in commit . I thought for a long time where we need to go back from floats to ints, as the ScrollingManager is now using floats for the view. Then I realized that the original code for `RectMap` already made a conversion to int. So I made similar changes in `HexMap` and `TmxObjectLayer`.

**Comment by ccanepa** [comment]
Ok with the change in HexMap.get_in_region.

But I would not change TmxObjectLayer. get_in_region : tmx objs does not align with an int grid so you may be testing an obj with left side at x=1.7, and a rect having  0 < x < 1.8. The overlap will be missed if we adopt the intified version.

**Comment by dangillet** [comment]
Hi,

Well spotted ! It makes now much more sense since I understand better what is `TmxObjectLayer`.

I made the necessary changes, rebased onto master and I'm merging into master.

Issue closed.
