### ISSUE TITLE
building cocos docs fails with pyglet 1.3rc1

### ISSUE THREAD

**Issue by ccanepa** [los-cocos/cocos#299]
building cocos docs fails with pyglet 1.3rc1

Found while preparing the 0.6.5 cocos release.

Built with
```
py -3.6 -m pip install sphinx
set SPHINXDIR=c:\python36\Scripts
cd F:\dev\cocos2017\docgen
make clean
make html
```
The sphinx log shows
```
# Sphinx version: 1.6.3
# Python version: 3.6.1 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\sphinx\cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "c:\python36\lib\site-packages\sphinx\application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "c:\python36\lib\site-packages\sphinx\config.py", line 150, in __init__
    execfile_(filename, config)
  File "c:\python36\lib\site-packages\sphinx\util\pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 42, in <module>
    director.init(300,100)
  File "F:\dev\cocos2017\cocos\director.py", line 327, in init
    self.window = window.Window(*args, **kwargs)
  File "F:\dev\pyglet\pyglet\window\__init__.py", line 504, in __init__
    screen = display.get_default_screen()
  File "F:\dev\pyglet\pyglet\canvas\base.py", line 73, in get_default_screen
    return self.get_screens()[0]
  File "F:\dev\pyglet\pyglet\canvas\base.py", line 65, in get_screens
    raise NotImplementedError('abstract')
NotImplementedError: abstract
```

Is not a showstopper just now because the docs can be built with pyglet 1.2.4 , but it may be a problem in future releases.

**Comment by ccanepa** [comment]
Knowing that recently the pyglet doc toolchain was adjusted I asked in their issue tracker, while they have it fresh.
https://bitbucket.org/pyglet/pyglet/issues/142/info-request-related-to-doc-building 

With luck it will be something they know and have a workaround.

**Comment by ccanepa** [comment]
Just to keep in mind, some changes where done to pyglet doc builder; I suspect that triggering the pyglet doc mode if detecting sphinx can broke the cocos doc build
