### ISSUE TITLE
test_batch AttributeError: 'GDIPlusFont' object has no attribute 'hfont'

### ISSUE THREAD

**Issue by ccanepa** [los-cocos/cocos#326]
Invalid, bad params passed.

After the seconf fix in #324 now test_batch crashes with:

```
(py-cocos) E:\dev\cocos2019\test>python test_batch.py
Traceback (most recent call last):
  File "test_batch.py", line 53, in <module>
    main()
  File "test_batch.py", line 50, in main
    director.run (main_scene)
  File "..\cocos\director.py", line 406, in run
    event_loop.run()
  File "e:\dev\pyglet-2019\pyglet\app\base.py", line 175, in run
    self._run()
  File "e:\dev\pyglet-2019\pyglet\app\base.py", line 187, in _run
    timeout = self.idle()
  File "e:\dev\pyglet-2019\pyglet\app\base.py", line 314, in idle
    window.dispatch_event('on_draw')
  File "e:\dev\pyglet-2019\pyglet\window\__init__.py", line 1330, in dispatch_ev
ent
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "e:\dev\pyglet-2019\pyglet\event.py", line 403, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler, exception)
  File "e:\dev\pyglet-2019\pyglet\event.py", line 466, in _raise_dispatch_except
ion
    raise exception
  File "e:\dev\pyglet-2019\pyglet\event.py", line 400, in dispatch_event
    if handler(*args):
  File "..\cocos\director.py", line 465, in on_draw
    self.fps_display.tick()
  File "..\cocos\fps.py", line 147, in tick
    self.label.update_info(self.fps, self.min_fps)
  File "..\cocos\fps.py", line 247, in update_info
    self.label.text = self.template.format(*args)
  File "e:\dev\pyglet-2019\pyglet\text\__init__.py", line 294, in text
    self.document.text = text
  File "e:\dev\pyglet-2019\pyglet\text\document.py", line 300, in text
    self.insert_text(0, text)
  File "e:\dev\pyglet-2019\pyglet\text\document.py", line 431, in insert_text
    self.dispatch_event('on_insert_text', start, text)
  File "e:\dev\pyglet-2019\pyglet\event.py", line 403, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler, exception)
  File "e:\dev\pyglet-2019\pyglet\event.py", line 466, in _raise_dispatch_except
ion
    raise exception
  File "e:\dev\pyglet-2019\pyglet\event.py", line 400, in dispatch_event
    if handler(*args):
  File "e:\dev\pyglet-2019\pyglet\text\layout.py", line 1045, in on_insert_text
    self._init_document()
  File "e:\dev\pyglet-2019\pyglet\text\layout.py", line 1034, in _init_document
    self._update()
  File "e:\dev\pyglet-2019\pyglet\text\layout.py", line 957, in _update
    lines = self._get_lines()
  File "e:\dev\pyglet-2019\pyglet\text\layout.py", line 933, in _get_lines
    glyphs = self._get_glyphs()
  File "e:\dev\pyglet-2019\pyglet\text\layout.py", line 1069, in _get_glyphs
    self._document.get_font_runs(dpi=self._dpi),
  File "e:\dev\pyglet-2019\pyglet\text\document.py", line 614, in get_font_runs
    ft = self.get_font(dpi=dpi)
  File "e:\dev\pyglet-2019\pyglet\text\document.py", line 624, in get_font
    bold=bool(bold), italic=bool(italic), dpi=dpi)
  File "e:\dev\pyglet-2019\pyglet\font\__init__.py", line 137, in load
    font = _font_class(name, size, bold=bold, italic=italic, dpi=dpi)
  File "e:\dev\pyglet-2019\pyglet\font\win32.py", line 493, in __init__
    super(GDIPlusFont, self).__init__(name, size, bold, italic, dpi)
  File "e:\dev\pyglet-2019\pyglet\font\win32.py", line 234, in __init__
    self.logfont = self.get_logfont(name, size, bold, italic, dpi)
  File "e:\dev\pyglet-2019\pyglet\font\win32.py", line 266, in get_logfont
    logfont.lfFaceName = asbytes(name)
  File "e:\dev\pyglet-2019\pyglet\compat.py", line 79, in asbytes
    return bytes(s)
TypeError: cannot convert 'GDIPlusFont' object to bytes
Exception ignored in: <function GDIPlusFont.__del__ at 0x000000000668C840>
Traceback (most recent call last):
  File "e:\dev\pyglet-2019\pyglet\font\win32.py", line 533, in __del__
  File "e:\dev\pyglet-2019\pyglet\font\win32.py", line 248, in __del__
AttributeError: 'GDIPlusFont' object has no attribute 'hfont'
```
win7 64.bits, python 3.7

pyglet:
commit 58dfdb6314fc900cfbba6355b79bb09e718a41c9 master github
Author: Benjamin Moran
Date: Fri Aug 9 09:43:50 2019 +0900

cocos:
commit 4282ecbf88217f756af1fed5df15bf894a9bc36f  master,
Author: Claudio Canepa 
Date:   Sun Aug 11 23:27:02 2019 -0300

**Comment by ccanepa** [comment]
repro same style crash with a pure pyglet bugdemo, opened 
https://github.com/pyglet/pyglet/issues/41

**Comment by ccanepa** [comment]
closed, invalid. see #327
