### ISSUE TITLE
Python 3.9 failures: AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

### ISSUE THREAD

**Issue by JJ1SLR** [los-cocos/cocos#337]
cocos.tiles.load_tmx() fails on Python 3.9.
```
Traceback (most recent call last):
  File "C:\xxxxxx\main.py", line 58, in <module>
    map = load("map.tmx")
  File "C:\xxxxxx\venv\lib\site-packages\cocos\tiles.py", line 218, in load
    obj = load_tmx(filename)
  File "C:\xxxxxx\venv\lib\site-packages\cocos\tiles.py", line 321, in load_tmx
    for c in tag.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

**Comment by JJ1SLR** [comment]
The problem looks like not exist in master branch, but in the release version 0.6.8.
Sorry for my mistake and I will close this issue.

**Comment by JJ1SLR** [comment]
I think it's better to release a new version that compact with Python 3.9. And sorry I reopen this issue.

**Comment by ccanepa** [comment]
Hi, @JJ1SLR , thanks for your report.

I see it is still an issue for python 3.9 in current master, where 4 of test/test_* fail, by example

```
(3.9.0) D:\cla\dev2\cocos-testcmp\work\cocos\test>python test_tiles.py
Traceback (most recent call last):
  File "D:\cla\dev2\cocos-testcmp\work\cocos\test\test_tiles.py", line 65, in <module>
    main()
  File "D:\cla\dev2\cocos-testcmp\work\cocos\test\test_tiles.py", line 43, in main
    test_layer = tiles.load('road-map.xml')['map0']
  File "D:\cla\dev2\cocos-testcmp\work\cocos\test\..\cocos\tiles.py", line 228, in load
    obj = load_tiles(filename)
  File "D:\cla\dev2\cocos-testcmp\work\cocos\test\..\cocos\tiles.py", line 241, in load_tiles
    resource.handle(root)
  File "D:\cla\dev2\cocos-testcmp\work\cocos\test\..\cocos\tiles.py", line 123, in handle
    return self.factories[tag.tag](self, tag)
  File "D:\cla\dev2\cocos-testcmp\work\cocos\test\..\cocos\tiles.py", line 188, in resource_factory
    self.handle(child)
  File "D:\cla\dev2\cocos-testcmp\work\cocos\test\..\cocos\tiles.py", line 123, in handle
    return self.factories[tag.tag](self, tag)
  File "D:\cla\dev2\cocos-testcmp\work\cocos\test\..\cocos\tiles.py", line 782, in rectmap_factory
    for i, column in enumerate(tag.getiterator('column')):
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
```

In the py38 docs, the section about 'xml.etree.ElementTree.Element' tells
  - getiterator: Deprecated since version 3.2, will be removed in version 3.9: Use method Element.iter() instead.
  - iter: New in version 3.2

iter has also been backported to 2.7

replacing as sugested, that particular error disapears, scripts run ok except for one:

test_tmxobjectlayer.py
```
Traceback (most recent call last):
  File "D:\cla\dev2\cocos-testcmp\support\proxy_snapshots.py", line 117, in <module>
    main(*sys.argv[1:])
  File "D:\cla\dev2\cocos-testcmp\support\proxy_snapshots.py", line 114, in main
    script_module.main()
  File "D:\cla\dev2\cocos-testcmp\work\test\test_tmxobjectlayer.py", line 40, in main
    maploaded = tiles.load('obj.tmx')
  File "d:\cla\dev2\cocos-testcmp\work\cocos\cocos\tiles.py", line 226, in load
    obj = load_tmx(filename)
  File "d:\cla\dev2\cocos-testcmp\work\cocos\cocos\tiles.py", line 415, in load_tmx
    layer = TmxObjectLayer.fromxml(tag, tilesets, map_height_pixels)
  File "d:\cla\dev2\cocos-testcmp\work\cocos\cocos\tiles.py", line 1879, in fromxml
    layer.objects.append(TmxObject.fromxml(obj, tilesets, map_height))
  File "d:\cla\dev2\cocos-testcmp\work\cocos\cocos\tiles.py", line 1801, in fromxml
    for c in tag.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```
...
(to be continued)

**Comment by ccanepa** [comment]
Similar findings than before :
py38 docs: getchildren()
	Deprecated since version 3.2, will be removed in version 3.9: Use list(elem) or iteration.
py27 similar warning

Well, trying the replacement
`	for c in tag.getchildren(): `
by
`	for c in tag:`

and testing: all scripts in cocos/test/ run normal: no tracebaks, drawings normal.

So, fixed in master 8367d9635 "more fix tiles for py 3.9+ xml changes"

A release will follow shortly (days, must be in this week because I late to other things)
Will close the issue after release.

**Comment by JJ1SLR** [comment]
Thanks ccanepa for the quickly answer and the fix!

**Comment by ccanepa** [comment]
released!
