### ISSUE TITLE
`pip install cocos2d` in python3.11 will raise error

### ISSUE THREAD

**Issue by dantezhu** [los-cocos/cocos#356]
1. execute cmd `pip install cocos2d` in python3.11
2. raise such error
    ```
    PS C:\Users\dantezhu> pip install cocos2d
    Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
    Collecting cocos2d
      Downloading https://mirrors.aliyun.com/pypi/packages/2f/45/d3efb5f3e635adc5b49ee2b890910c672f4c98b927a820230abadde9c9bf/cocos2d-0.6.9.tar.gz (4.7 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 6.3 MB/s eta 0:00:00
      Preparing metadata (setup.py) ... error
      error: subprocess-exited-with-error
      
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [7 lines of output]
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "C:\Users\dantezhu\AppData\Local\Temp\pip-install-zor1doi2\cocos2d_eb6b1a6aeb7c4500be9ebf08cedc9408\setup.py", line 38, in <module>
              f = open('README.rst','rU')
                  ^^^^^^^^^^^^^^^^^^^^^^^
          ValueError: invalid mode: 'rU'
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed

    × Encountered error while generating package metadata.
    ╰─> See above for output.

    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    ```

**Comment by dangillet** [comment]
Thank you for the report. The issue is resolved by https://github.com/los-cocos/cocos/pull/355
